package com.healthfit.macroplus.services

import com.healthfit.macroplus.models.User
import com.healthfit.macroplus.repositories.UserRepository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.util.UUID


/*
"Transactional" means that if an error happens halfway though the function
then we just roll back to before we started to make changes.
This means that we don't end up with half saved data within the database
 */



@Service
class UserService(
  private val userRepository: UserRepository
) {

  @Transactional
  fun registerUser(email: String, heightCm: Int): User {

	if (userRepository.existsByEmail(email)) {
	  throw IllegalArgumentException("User with email '$email' already exists.")
	}

//	ID is generated by hibernate automatically
	val newUser = User(
	  email = email,
	  heightCm = heightCm
	)

	return userRepository.save(newUser)
  }

  fun getUserById(id: UUID): User {
	return userRepository.findById(id)
	  .orElseThrow { NoSuchElementException("User not found with ID: $id") }
  }


  @Transactional
  fun updateUserHeight(userId: UUID, newHeightCm: Int): User {
	val user = getUserById(userId)
	user.heightCm = newHeightCm
	return userRepository.save(user)
  }
}