ALTER TABLE user_goals ALTER COLUMN target_protein_g TYPE DECIMAL(8, 2);
ALTER TABLE user_goals ALTER COLUMN target_carbs_g TYPE DECIMAL(8, 2);
ALTER TABLE user_goals ALTER COLUMN target_fats_g TYPE DECIMAL(8, 2);

ALTER TABLE foods ALTER COLUMN protein_per_100g TYPE DECIMAL(8, 2);
ALTER TABLE foods ALTER COLUMN carbs_per_100g TYPE DECIMAL(8, 2);
ALTER TABLE foods ALTER COLUMN fats_per_100g TYPE DECIMAL(8, 2);
ALTER TABLE foods ALTER COLUMN serving_size_g TYPE DECIMAL(8, 2);

ALTER TABLE food_logs ALTER COLUMN protein_g TYPE DECIMAL(8, 2);
ALTER TABLE food_logs ALTER COLUMN carbs_g TYPE DECIMAL(8, 2);
ALTER TABLE food_logs ALTER COLUMN fats_g TYPE DECIMAL(8, 2);
ALTER TABLE food_logs ALTER COLUMN quantity_g TYPE DECIMAL(8, 2);

ALTER TABLE weigh_ins ALTER COLUMN weight_kg TYPE DECIMAL(8, 2);
